FAA_ref 89408: enable application validation on submission tag
dchbx/enroll pull request #3870
Opened 2020-09-01 15:57 UTC by vkghub

### Master Redmine ticket
* (89408)

### Child Redmine ticket(s)
* ()
* ()

### Local build result

```
bundle exec rake parallel:spec[4]
bundle exec cucumber
```

### Latest rebase/merge tag
*

---

### Data ticket(s) Followup
* (redmine links here - optional)

### Related Pull Requests
* (github links here - optional)

---

### TODOs / Notes
#### Peer Review
* (For code review)

#### Functional Testing
* (For testing locally)

#### Deployment
* (for release manager and/or build manager)

2020-09-02 19:12 UTC, saipraveen18 approved these changes

2020-09-02 19:54 UTC, bill-transue approved these changes
Fixes application validation.

2020-09-02 19:56 UTC, bill-transue requested changes
Let's please bring those pregnancy cucumber scenarios back.

2020-09-03 12:46 UTC, bill-transue approved these changes

2020-09-03 12:46 UTC, merged