fix namespacing benefit_applications operations
dchbx/enroll pull request #4015
Opened 2020-11-05 16:30 UTC by saikumar9

### Master Redmine ticket
* (Required!)

### Child Redmine ticket(s)
* ()
* ()

### Local build result

```
bundle exec rake parallel:spec[4]
bundle exec cucumber
```

### Latest rebase/merge tag
*

---

### Data ticket(s) Followup
* (redmine links here - optional)

### Related Pull Requests
* (github links here - optional)

---

### TODOs / Notes
#### Peer Review
* (For code review)

#### Functional Testing
* (For testing locally)

#### Deployment
* (for release manager and/or build manager)

2020-11-16 21:34 UTC, raghuramg requested changes
Added comments inline.

2020-12-04 16:55 UTC, raghuramg requested changes
Please make suggested changes to the code

2020-12-04 16:55 UTC, raghuramg commented on components/benefit_sponsors/app/domain/benefit_sponsors/operations/benefit_applications/clone.rb
> +        def clone_benefit_application(ba_entity, values)
model_class.new(entity.to_h) should work here. add entities, contracts for STI models instead of _type.

2020-12-04 16:55 UTC, raghuramg commented on components/benefit_markets/app/domain/benefit_markets/operations/benefit_sponsor_catalogs/clone.rb
> +          benefit_sponsor_catalog = yield init_benefit_sponsor_catalog(values)
modify this with following steps...

1. clone attributes from original catalog
2. create entity using benefit sponsor catalog 'create' operation
3. convert entity to model (model_class.new(entity.to_h))

2020-12-04 16:55 UTC, raghuramg commented on components/benefit_sponsors/app/domain/benefit_sponsors/entities/sponsored_benefit.rb
> +      attribute :_type,                       Types::Strict::String.optional.meta(omittable: true)
remove _type from entities...instead create entities for STI models

2020-12-04 16:55 UTC, raghuramg commented on components/benefit_sponsors/app/domain/benefit_sponsors/validators/sponsored_benefits/sponsored_benefit_contract.rb
> +          optional(:_type).maybe(:string)
remove _type

2020-12-04 17:29 UTC, raghuramg requested changes
Added more feedback

2020-12-04 17:29 UTC, raghuramg commented on components/benefit_sponsors/app/domain/benefit_sponsors/operations/benefit_applications/reinstate.rb
> +            (@current_ba.terminated_on + 1.day)..@current_ba.effective_period.max
terminated_on field populated with date on which user triggered termination.
we shorten the application based on last day of coverage.

ex. benefit application 1/1/2020 - 1/31/2020
      user triggered termination on 11/5, following will be the dates on application
      terminated_on: 11/5/2020
      effective_period: 1/1/2020 - 11/30/2020

2020-12-04 17:29 UTC, raghuramg commented on components/benefit_sponsors/app/domain/benefit_sponsors/operations/benefit_applications/reinstate.rb
> +            (@current_ba.terminated_on + 1.day)..@current_ba.effective_period.max
Please revisit this logic.

2020-12-11 14:02 UTC, saikumar9 commented on components/benefit_sponsors/app/domain/benefit_sponsors/operations/benefit_applications/reinstate.rb
> +          valid_states_for_reinstatement = [:terminated, :termination_pending, :canceled]
This will be handled in ticket #90812.

2020-12-11 14:02 UTC, saikumar9 commented on components/benefit_sponsors/app/domain/benefit_sponsors/operations/benefit_applications/reinstate.rb
> +          when :canceled
retroactive_canceled will be handled in a separate ticket #90812.

2020-12-11 14:03 UTC, saikumar9 commented on components/benefit_sponsors/app/domain/benefit_sponsors/operations/benefit_applications/reinstate.rb
> +        def initial_ba_within_valid_timeframe?
Made changes as per suggestions.

2020-12-11 14:03 UTC, saikumar9 commented on components/benefit_sponsors/app/domain/benefit_sponsors/operations/benefit_applications/clone.rb
> +        def clone_benefit_application(ba_entity, values)
Added SYI models and removed the dependency from _type.

2020-12-11 14:04 UTC, saikumar9 commented on components/benefit_sponsors/app/domain/benefit_sponsors/operations/benefit_applications/reinstate.rb
> +            (@current_ba.terminated_on + 1.day)..@current_ba.effective_period.max
Good catch! Refactored code as per suggestions.

2020-12-14 17:05 UTC, raghuramg approved these changes
reviewed updated changes. please promote this for testing

2020-12-16 15:13 UTC, merged