Add check for off cycle renewals to notices
dchbx/enroll pull request #4022
Opened 2020-11-06 22:41 UTC by RyanEddyIC

### Master Redmine ticket
* (Required!)

### Child Redmine ticket(s)
* ()
* ()

### Local build result

```
bundle exec rake parallel:spec[4]
bundle exec cucumber
```

### Latest rebase/merge tag
*

---

### Data ticket(s) Followup
* (redmine links here - optional)

### Related Pull Requests
* (github links here - optional)

---

### TODOs / Notes
#### Peer Review
* (For code review)

#### Functional Testing
* (For testing locally)

#### Deployment
* (for release manager and/or build manager)

2020-11-10 17:33 UTC, jayreddy519 approved these changes

2020-11-12 16:15 UTC, ymhari requested changes

2020-11-12 16:15 UTC, ymhari commented on components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
> +        if is_off_cycle?
Can we use something like `benefit_application.is_renewing?` ?

2020-11-18 16:14 UTC, jayreddy519 approved these changes

2020-12-17 21:52 UTC, closed without merging