Story 90765
dchbx/enroll pull request #4030
Opened 2020-11-12 17:57 UTC by saimekala07

### Master Redmine ticket
* (Required!)

### Child Redmine ticket(s)
* ()
* ()

### Local build result

```
bundle exec rake parallel:spec[4]
bundle exec cucumber
```

### Latest rebase/merge tag
*

---

### Data ticket(s) Followup
* (redmine links here - optional)

### Related Pull Requests
* (github links here - optional)

---

### TODOs / Notes
#### Peer Review
* (For code review)

#### Functional Testing
* (For testing locally)

#### Deployment
* (for release manager and/or build manager)

2020-12-02 22:49 UTC, raghuramg requested changes
Code changes looks good.

Added small suggestions with regard to code refactor.

2020-12-02 22:49 UTC, raghuramg commented on components/benefit_sponsors/app/models/benefit_sponsors/benefit_packages/benefit_package.rb
> +              hbx_enrollment.update_attribute(:terminate_reason, "retroactive_canceled") if benefit_application.retroactive_canceled?
use
`  hbx_enrollment.terminate_reason = 'retroactive_canceled' 
`
this attribute saved in the next line hbx_enrollment.cancel_coverage!

2020-12-02 22:49 UTC, raghuramg commented on components/benefit_sponsors/app/models/benefit_sponsors/benefit_packages/benefit_package.rb
> +              hbx_enrollment.update_attribute(:terminate_reason, "retroactive_canceled") if benefit_application.retroactive_canceled?
can you also modify if conditions in the method like below.
```
hbx_enrollment.cancel_coverage!
hbx_enrollment.notify_enrollment_cancel_or_termination_event(enrollment_notify_flag(enroll_notify)) unless hbx_enrollment.inactive?
```

2020-12-02 22:49 UTC, raghuramg commented on components/benefit_sponsors/spec/models/benefit_sponsors/benefit_packages/benefit_package_spec.rb
> +        before do
replace this with 
`   let(:renewal_state) { :canceled }`

2020-12-02 22:49 UTC, raghuramg commented on components/benefit_sponsors/spec/models/benefit_sponsors/benefit_packages/benefit_package_spec.rb
> +        before :each do
replace this with

`let(:renewal_state) { :retroactive_canceled }`

2020-12-03 22:40 UTC, saimekala07 commented on components/benefit_sponsors/spec/models/benefit_sponsors/benefit_packages/benefit_package_spec.rb
> +        before do
updated

2020-12-03 22:40 UTC, saimekala07 commented on components/benefit_sponsors/spec/models/benefit_sponsors/benefit_packages/benefit_package_spec.rb
> +        before :each do
updated

2020-12-03 22:43 UTC, saimekala07 commented on components/benefit_sponsors/app/models/benefit_sponsors/benefit_packages/benefit_package.rb
> +              hbx_enrollment.update_attribute(:terminate_reason, "retroactive_canceled") if benefit_application.retroactive_canceled?
updated "update_attribute" statement.

After enrollment canceled persisted, hbx_enrollment.inactive? returns false. will trigger for waived enrollmnets

2020-12-07 14:11 UTC, raghuramg approved these changes
Added retroactive_canceled state benefit application. Reviewed code and specs. Please promote this for testing.

2020-12-16 14:58 UTC, merged