90744: PY Reinstate - UI
dchbx/enroll pull request #4031
Opened 2020-11-12 18:30 UTC by nks2109

### Master Redmine ticket
* (Required!)

### Child Redmine ticket(s)
* ()
* ()

### Local build result

```
bundle exec rake parallel:spec[4]
bundle exec cucumber
```

### Latest rebase/merge tag
*

---

### Data ticket(s) Followup
* (redmine links here - optional)

### Related Pull Requests
* (github links here - optional)

---

### TODOs / Notes
#### Peer Review
* (For code review)

#### Functional Testing
* (For testing locally)

#### Deployment
* (for release manager and/or build manager)

2020-12-08 13:23 UTC, raghuramg requested changes
please make suggested changes. thank you

2020-12-08 13:23 UTC, raghuramg commented on app/helpers/employers/employer_helper.rb
> +    current_month = TimeKeeper.date_of_record.beginning_of_month
you can do 

`application.benefit_sponsor_catalog.effective_period.cover(TimeKeeper.date_of_record)`

instead of hard coded months.

2020-12-08 14:05 UTC, raghuramg requested changes

2020-12-08 14:05 UTC, raghuramg commented on app/views/exchanges/employer_applications/_reinstate_benefit_application_modal.html.erb
> +        <h4>Would you like to reinstate the plan year?</h4>
Replace with locales (add translation key)

2020-12-08 14:05 UTC, raghuramg commented on app/views/exchanges/employer_applications/_reinstate_benefit_application_modal.html.erb
> +        <%= link_to "Continue", exchanges_employer_application_reinstate_path({employer_application_id: application.id, employer_id: application.benefit_sponsorship.id}), method: :put, remote: true,
Replace Continue and Cancel with translation keys

2020-12-08 16:54 UTC, nks2109 commented on app/helpers/employers/employer_helper.rb
> +    current_month = TimeKeeper.date_of_record.beginning_of_month
We should display the reinstate button for the last 11 months from the current month, not for the entire 12 months period.

2020-12-08 17:14 UTC, nks2109 commented on app/views/exchanges/employer_applications/_reinstate_benefit_application_modal.html.erb
> +        <h4>Would you like to reinstate the plan year?</h4>
sure, thanks

2020-12-15 00:03 UTC, raghuramg requested changes
requested missing translation

2020-12-15 00:03 UTC, raghuramg commented on app/controllers/exchanges/employer_applications_controller.rb
> +      flash[:notice] = "#{@benefit_sponsorship.legal_name} - Plan Year Reinstated Successfully Effective #{effective_date}"
Add translation for this

2020-12-15 03:26 UTC, saimekala07 commented on app/controllers/exchanges/employer_applications_controller.rb
> +      flash[:notice] = "#{@benefit_sponsorship.legal_name} - Plan Year Reinstated Successfully Effective #{effective_date}"
Added translation.

2020-12-16 14:23 UTC, raghuramg approved these changes
All the feedback addressed. Please promote this for testing

2020-12-16 14:41 UTC, merged