Refs #90809, wip - Operation to reinstate enrollments with tests
dchbx/enroll pull request #4034
Opened 2020-11-12 22:09 UTC by saikumar9

### Master Redmine ticket
* (Required!)

### Child Redmine ticket(s)
* ()
* ()

### Local build result

```
bundle exec rake parallel:spec[4]
bundle exec cucumber
```

### Latest rebase/merge tag
*

---

### Data ticket(s) Followup
* (redmine links here - optional)

### Related Pull Requests
* (github links here - optional)

---

### TODOs / Notes
#### Peer Review
* (For code review)

#### Functional Testing
* (For testing locally)

#### Deployment
* (for release manager and/or build manager)

2020-12-14 18:08 UTC, raghuramg approved these changes
Code looks good. Please promote this for testing

2020-12-14 21:42 UTC, raghuramg requested changes
Please make suggested changes

2020-12-14 21:42 UTC, raghuramg commented on app/domain/operations/hbx_enrollments/reinstate.rb
> +        valid_enrs.any?{|ba| ba.effective_on >= @effective_on && ba.effective_on.year == @effective_on.year}
Modified logic to use sponsored_benefit_package.effective_period to verify if any enrollment exists within the application coverage period.

2020-12-15 03:06 UTC, saimekala07 commented on app/domain/operations/hbx_enrollments/reinstate.rb
> +        valid_enrs.any?{|ba| ba.effective_on >= @effective_on && ba.effective_on.year == @effective_on.year}
updated as per comments.

2020-12-16 15:14 UTC, merged