Ce multi bga display
dchbx/enroll pull request #4136
Opened 2020-12-23 22:28 UTC by saimekala07

### Master Redmine ticket
* (Required!)

### Child Redmine ticket(s)
* ()
* ()

### Local build result

```
bundle exec rake parallel:spec[4]
bundle exec cucumber
```

### Latest rebase/merge tag
*

---

### Data ticket(s) Followup
* (redmine links here - optional)

### Related Pull Requests
* (github links here - optional)

---

### TODOs / Notes
#### Peer Review
* (For code review)

#### Functional Testing
* (For testing locally)

#### Deployment
* (for release manager and/or build manager)

2021-01-08 23:52 UTC, raghuramg requested changes
Please verify the comments. thanks

2021-01-08 23:52 UTC, raghuramg commented on app/models/hbx_enrollment.rb
> +    return unless reinstated_package.present? || self.terminated_on != parent_reinstated_app.end_on
self.terminated_on != parent_reinstated_app.end_on seems like not possible. Can you provide use case where we need this check.

2021-01-11 23:24 UTC, saimekala07 commented on app/models/hbx_enrollment.rb
> +    return unless reinstated_package.present? || self.terminated_on != parent_reinstated_app.end_on
In method hbx_enrollment#update_existing_shop_coverage, when shopping under benefit application terminated/termination pending, the shopped enrollment(self here) will be terminated with benefit application termination date.

Here is the logic:

```
benefit_application = sponsored_benefit_package.benefit_application
return unless benefit_application.present? && benefit_application.terminated_on.present?
term_or_cancel_enrollment(self, benefit_application.terminated_on, benefit_application.termination_reason)
```

hbx_enrollment#update_reinstate_coverage,

Above method used In the scenario where any changes made parent reinstated enrollment, reinstated enrollment will be canceled and new reinstated enrollment created based on the new enrollment purchased.

2021-01-14 16:11 UTC, raghuramg approved these changes
Please promote this for testing

2021-01-14 18:21 UTC, merged