User story 91965
dchbx/enroll pull request #4181
Opened 2021-01-13 01:04 UTC by jayreddy519

### Master Redmine ticket
* (Required!)

### Child Redmine ticket(s)
* ()
* ()

### Local build result

```
bundle exec rake parallel:spec[4]
bundle exec cucumber
```

### Latest rebase/merge tag
*

---

### Data ticket(s) Followup
* (redmine links here - optional)

### Related Pull Requests
* (github links here - optional)

---

### TODOs / Notes
#### Peer Review
* (For code review)

#### Functional Testing
* (For testing locally)

#### Deployment
* (for release manager and/or build manager)

2021-01-14 22:15 UTC, saikumar9 requested changes
Please review the comments.

2021-01-14 22:15 UTC, saikumar9 commented on app/controllers/insured/plan_shoppings_controller.rb
> +      @hbx_enrollment.update_attributes(aggregate_aptc_amount: @max_aptc)
Please update the **aggregate_aptc_amount** on enrollment at the same place where we were updating **applied_aptc_amount** on the enrollment.

2021-01-14 22:15 UTC, saikumar9 commented on app/domain/operations/individual/apply_aggregate_to_enrollment.rb
> +        Success(params[:eligibility_determination])
Add validation to return a failure if the given enrollment non-ivl or dental enrollment.

2021-01-14 22:15 UTC, saikumar9 commented on spec/domain/operations/individual/apply_aggregate_to_enrollment_spec.rb
> +RSpec.describe Operations::Individual::ApplyAggregateToEnrollment do
Good test coverage.

2021-01-15 01:22 UTC, ymhari commented on app/controllers/insured/plan_shoppings_controller.rb
> +      @hbx_enrollment.update_attributes(aggregate_aptc_amount: @max_aptc)
Sai, as we discuss we should be updating the aggregate amount for shopping enrollments/during shopping as well and shopping enrollment does not necessarily have to go till the confirmation page where we update the applied aptc amount on enrollment.

2021-01-15 01:26 UTC, ymhari commented on app/domain/operations/individual/apply_aggregate_to_enrollment.rb
> +        Success(params[:eligibility_determination])
Sai, we are not sending enrollment as param here. Instead we fetch them in the operation where we take of these requirements through the scopes.

2021-01-15 14:20 UTC, saikumar9 approved these changes

2021-01-15 14:21 UTC, merged